apiVersion: v2
name: irsa-servicemonitors
version: 0.1.0-dev
description: IRSA ServiceMonitors
appVersion: 1.0.0
home: https://github.com/giantswarm/irsa-servicemonitors-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: phoenix
keywords:
  - monitoring
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
type: application
